[pytest]
python_files = test_*.py
markers =
    capitalize: тесты для метода capitalize
    positive: позитивные тесты
    negative: негативные тесты
    boundary: граничные случаи
    trim: тесты для метода trim 
    contains: тесты для метода contains
    delete_symbol: тесты для метода delete_symbol
    positive_test: тесты для калькулятора
    negative_test: негативные тесты